### ISSUE TITLE
Star repo - Add Jokes - send PR - Good First Issue

### ISSUE THREAD

**Issue by mohitrakhade20** [mohitrakhade20/javascript-jokes#60]
1. **Star Repo** 🌟
2. Add Joke or Meme 😃
3. Send PR 🐾
4. I will merge your repo 💯

**Comment by viraldevpb** [comment]
Hey, @mohitrakhade20 can u briefly explain this issue to me?

**Comment by mohitrakhade20** [comment]
two ways to contribute to this repo:
