### ISSUE TITLE
Create Code Of Conduct

### ISSUE THREAD

**Issue by mohitrakhade20** [mohitrakhade20/javascript-jokes#64]
You can take help of the other good projects on GitHub
Submit proper Code Of Conduct

**Comment by Rambo9901** [comment]
Ok , I can do this job for you ... 

Just tell me in which context do you mean to have "A Proper Code Of Conduct ?" Like of GitHub , of your repo or something else

**Comment by Rambo9901** [comment]
Please do tell . I'm willing to help you on this ...

**Comment by Srijan-Baniyal** [comment]
ok
